config/routes.rb
Rails.application.routes.draw do 
  
  resources :pins

  devise_for :users
  root 'home#index' 
  get  'home/about'
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base 
  belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
    has_many :pins
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  before_filter :configure_permitted_parameters, if: :devise_controller? 
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
  
  def about 
  end
end

app/controllers/pins_controller.rb
 class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
   
   respond_to :html

  def index
   @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
 end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
   if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
 end


  def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end
 end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container"> 
    
    <!-- Brand and toggle get grouped for better mobile display --> 
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
      <%= link_to "Blues Fans Pinterested Website!", root_path, class:"navbar-brand"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        
         <li><%= link_to "Home", root_path %></li>  
         <li><%= link_to "About", home_about_path %></li>
       
       <% if user_signed_in? %>  
         <li><%= link_to 'Add Pin', new_pin_path %></li>
          <li><%= link_to 'List Pins', pins_path %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li> 
         <li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
      
       <% else %> 
       <li><%= link_to "Login", new_user_session_path %></li> 
         <li><%=link_to "Sign Up", new_user_registration_path %></li>  
       <% end %>
        
                        
             
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->  

</nav>

app/views/home/about.html.erb
<h2>Everton Football Club 1878 - 2015 </h2>  
<div class="well">
<p> Welcome to the history of Everton Football Club. We have a glorious history founded on a rich tradition of innovation, bravery and determination to live up to the motto 'Nil Satis Nisi Optimum'. This interactive Timeline delivers our history via image galleries, articles, excerpts, video clips and social media links. Scroll using the tool above and utilise the zoom functionality to open up even more detail about the famous events in the history of a football club that has played more top flight games than any other.</p> 
  
  <h1>St Domingo's FC Formed</h1><br> 
  <p>Everton began their history as St Domingo's FC, playing their first match in the south-east corner of Stanley Park. St Domingo's Church had originally formed a cricket club and added football to their sports armoury.</p> 
  <h4><p>There is no place like Goodison Park when the place is full.</p></h4> 
  <p>The atmosphere is quite unique but when the current team enters the arena to the sound of Z-Cars and the deafening noise from over 40,000 spectators, it's difficult to imagine an Everton team trotting out onto a park pitch with no dressing rooms, carrying the goalposts!</p> 
  <p>But that's how it all began. </p> 
  <p>The predecessors of heroes such as Dean, Lawton, Hickson, Labone, Ball, Latchford, Sharp, Lineker and Ferguson, were as far removed from the 21st Century image of a football player as it's possible to be. </p> 
  <p>The St Domingo Methodist Church Sunday School was opened in May 1870 and eight years later the football team using the St Domingo name played its first match in the south-east corner of Stanley Park, with the players carrying the posts from the park lodge on Mill Lane before fixing them into the metal sockets at either end of the crudely marked pitch. </p> 
  <h4><p>St Domingo's FC quickly established a local reputation for themselves and players were recruited from outside of the parish, precipitating a change of name in November 1879 - to EVERTON. </p></h4> 
  <p>The first game as Everton Football Club took place on December 20th 1879 at Stanley Park against St Peter's. Wearing blue and white striped shirts, Everton won 6-0, although, sadly, there are no records of line-ups or goalscorers. </p>

app/views/home/index.html.erb
<div class="jumbotron center">   
   
    <h2>Welcome To My Everton FC Pinterested App</h2>
         <h5>* Join today and post your own teams pictures *</h5>

         <% if user_signed_in? %> 
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %> 
              <%= link_to "Edit Profile", edit_user_registration_path,class: 'btn btn-success'  %> 
               <%= link_to 'List Pins', pins_path, class: 'btn btn-primary' %>  
                  
       <% else %>
          <%= link_to "Login", new_user_session_path, class: 'btn btn-success' %> 
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'%> 
          
        <% end %>
  <br> 

  <div class="responsive-video "><iframe src="//player.vimeo.com/video/48076577" width="200" height="200" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>  <h3>Nil Satis Nisi Optimum </h3><div> <h5>"nothing but the best is good enough"</h5> 
   <div>
     <h5>Everton Football Club</h5>

    
</div>     
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterested</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
 
  
 
  <%= render "home/header" %>
<div class="container">   
  
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-success") %>
  <% end %>
  
  
  <%= yield %> 
 </div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

      <div class="form-group">
       <%= f.label :description %><br>
       <%= f.text_field :description, class: "form-control" %>
     </div>
   
      <div class="form-group">
       <%= f.label :image %>
       <%= f.file_field :image, class: "form-control" %>
     </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">  

     <div class="panel panel-primary">
     <div class="panel-heading"><h2>Editing pin</h2></div> 
     <div class="panel-body">  
        <%= render 'form' %> 
       <div> 
          
        <div class="panel-footer"><%= link_to 'Show', @pin %> 
          <%= link_to 'Back', pins_path  %>
         </div>
       </div>
 

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %> 



  <div class="box"> 
       <div class="panel panel-default">
                 <%= link_to image_tag(pin.image.url(:medium)), pin %><br/> 
              <div class="panel-body">
                 <%= pin.description %><br>
                <strong><%= pin.user.name if pin.user %></strong><br> 
                </div>
                  <% if pin.user == current_user %> 
              <div class="panel-footer">
                 <%= link_to 'Edit', edit_pin_path(pin) %>
                 <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %><br/> 
              </div>
            <% end %> 
           </div>  
        </div>
    <% end %>
   </div> 
 
<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
 <div class="row">
    <div class="col-md-6 col-md-offset-3">  

     <div class="panel panel-primary">
     <div class="panel-heading"><h2>New pin</h2></div> 
     <div class="panel-body"> 

        <%= render 'form' %>
   </div>
       <div class="panel-footer"><%= link_to 'Back', pins_path %></div>
 
      </div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>
 

<div class="row">
   <div class="col-md-offset-2 col-md-8">
    
     <div class="panel panel-default">
       <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %><div>
       <div class="panel-body">
          
           <%= @pin.description %><br/>
        
         <strong><%= @pin.user.name %></strong><br/>
        
         <% if @pin.user == current_user %>
           <%= link_to 'Edit', edit_pin_path(@pin) %> |
         <% end %>
         <%= link_to 'Back', pins_path %>
         <div>
     <div>
   <div>
 <div>